server:
  port: 8090
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-3-21-44-11.us-east-2.compute.amazonaws.com:3306/TSADMIN?serverTimezone=Asia/Seoul
    username: tsadmin
    password: 1qaz!QAZ

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      format_sql: true
      show_sql: true
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false

logging:
  level:
    org:
      springframework:
        web: DEBUG
        data:
          jpa: DEBUG
      hibernate:
        sql: TRACE
    jpa: DEBUG

jwt:
  header: Authorization
  #HS512 ????? ??? ??? ??? 512bit, ? 64byte ??? secret key? ???? ??.
  #echo 'puerpuella-apitextssul-springboot-react-back-front-isolation-i-love-you-and-we-are-the-one'|base64
  secret: cHVlcnB1ZWxsYS10aGVsYWJ5cmludGgtc3ByaW5nYm9vdC1yZWFjdC1iYWNrLWZyb250LWlzb2xhdGlvbi1pLWxvdmUteW91LWFuZC13ZS1hcmUtdGhlLW9uZQ==
  token-validity-in-seconds: 3600

kr:
  co:
    puerpuella:
      apitextssul:
        image_path: /home/ec2-user/file/ts