

DROP TABLE TB_COMMENT;
DROP TABLE TMP_ARTICLE_LIKE;
DROP TABLE TB_ARTICLE;
DROP TABLE TB_MEMBER;
CREATE TABLE TB_MEMBER(
	UID int AUTO_INCREMENT,
	EMAIL varchar(255),
	NICKNAME varchar(16),
	PASSWORD varchar(255),
	ROLE int,
	CREATE_UID int,
	CREATE_DT datetime,
	CREATE_IP varchar(15),
	UPDATE_UID int,
	UPDATE_DT datetime,
	UPDATE_IP varchar(15),

	PRIMARY KEY (UID)
);
CREATE TABLE TB_ARTICLE(
	ARTICLE_ID int AUTO_INCREMENT,
	ARTICLE_TYPE_ID tinyint,
	ARTICLE_CATEGORY_ID tinyint,
	ARTICLE_TITLE varchar(255),
	CONTENT longtext,
	VIEW_CNT int,
	CREATE_UID int,
	CREATE_DT datetime,
	CREATE_IP varchar(15),
	UPDATE_UID int,
	UPDATE_DT datetime,
	UPDATE_IP varchar(15),
	PRIMARY KEY (ARTICLE_ID)
);
CREATE TABLE TB_COMMENT(
	COMMENT_ID int AUTO_INCREMENT,
	ARTICLE_ID int,
	COMMENT longtext,
	CREATE_UID int,
	CREATE_DT datetime,
	CREATE_IP varchar(15),
	UPDATE_UID int,
	UPDATE_DT datetime,
	UPDATE_IP varchar(15),
	PRIMARY KEY (COMMENT_ID)
);
CREATE TABLE TMP_ARTICLE_LIKE(
	ARTICLE_ID int,
	CREATE_UID int,
	CREATE_DT datetime,
	CREATE_IP varchar(15),
	UPDATE_UID int,
	UPDATE_DT datetime,
	UPDATE_IP varchar(15),
	PRIMARY KEY (ARTICLE_ID, CREATE_UID)
);


